name: Test

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.x

      - name: check formatting
        run: deno fmt --check

      - name: check linting
        run: deno lint

      - name: run tests
        run: deno task test